define([], function() {
  return {
    "SpecialNewsSliderPropertyPageGeneralPanel": "Customize the general settings",
    "SpecialNewsSliderPropertyPageTextPanel": "Customize the Text Panel settings",
    "SpecialNewsSliderGeneralPanelDataGroupName": "Data",
    "SpecialNewsSliderGeneralPanelGroupName": "General",
    "SpecialNewsSliderTextPanelGroupName": "Text Panel",
    "SpecialNewsSliderTextPanelEnableFieldLabel": "Enable text panel",
    "SpecialNewsSliderTextPanelAlwaysOnTopFieldLabel": "Always on top",
    "SpecialNewsSliderTextPanelOpacityFieldLabel": "Opacity",
    "SpecialNewsSliderTextPanelFontFieldLabel": "Font",
    "SpecialNewsSliderTextPanelFontSizeFieldLabel": "Font Size",
    "SpecialNewsSliderTextPanelBackgroundColorFieldLabel": "Background Color",
    "SpecialNewsSliderTextPanelAlignFieldLabel": "Text align",
    "SpecialNewsSliderTextPanelFontColorFieldLabel": "Font Color",
    "SpecialNewsSliderNoDataMessage": "Please edit the web part and add news items.",
    "SpecialNewsSliderGeneralPanelEffectsGroupName": "Effects",
    "SpecialNewsSliderGeneralPanelTransitionDropdownLabel": "Transition",
    "SpecialNewsSliderGeneralPanelTransitionDropdownSlideOptionText":"Slide",
    "SpecialNewsSliderGeneralPanelTransitionDropdownFadeOptionText":"Fade",
    "SpecialNewsSliderGeneralPanelEnableProgressIndicatorToggleLabel": "Enable Progress Indicator",
    "SpecialNewsSliderGeneralPanelEnableArrowsToggleLabel": "Enable Arrows",
    "SpecialNewsSliderGeneralPanelEnableBulletsToggleLabel": "Enable Bullets",
    "SpecialNewsSliderGeneralPanelEnablePlayToggleLabel": "Enable Play Button",
    "SpecialNewsSliderGeneralPanelEnableFullscreenToggleLabel": "Enable Fullscreen Button",
    "SpecialNewsSliderGeneralPanelEnableZoomPanelToggleLabel": "Enable Zoom Panel",
    "SpecialNewsSliderGeneralPanelControlsAlwaysOnToggleLabel": "Controls Always On",
    "SpecialNewsSliderGeneralPanelPreserveRatioToggleLabel": "Preserve Ratio",
    "SpecialNewsSliderGeneralPanelPauseOnMouseoverToggleLabel": "Pause On Mouseover",
    "SpecialNewsSliderGeneralPanelCarouselToggleLabel": "Carousel",
    "SpecialNewsSliderGeneralPanelAutoplayToggleLabel": "Autoplay",
    "SpecialNewsSliderGeneralPanelSpeedSliderLabel": "Speed (ms)",
    "SpecialNewsSliderGeneralPanelDataManagementLabel": "Sources",
    "SpecialNewsSliderGeneralPanelDataManagementTableHeaderText": "Manage Data Sources",
    "SpecialNewsSliderGeneralPanelDataManagementTableTitleColumnDisplayName":"Title",
    "SpecialNewsSliderGeneralPanelDataManagementTableEnableColumnDisplayName":"Enable",
    "SpecialNewsSliderGeneralPanelDataManagementTableDescriptionColumnDisplayName":"Description",
    "SpecialNewsSliderGeneralPanelDataManagementTablePictureColumnDisplayName":"Picture",
    "SpecialNewsSliderGeneralPanelDataManagementTableLinkUrlColumnDisplayName":"LinkUrl"
  }
});