define([], function() {
  return {
    "SpecialNewsSliderPropertyPageGeneralPanel": "常规设置",
    "SpecialNewsSliderPropertyPageTextPanel": "文本面板设置",
    "SpecialNewsSliderGeneralPanelDataGroupName": "数据",
    "SpecialNewsSliderGeneralPanelGroupName": "常规",
    "SpecialNewsSliderTextPanelGroupName": "文本",
    "SpecialNewsSliderTextPanelEnableFieldLabel": "显示文本",
    "SpecialNewsSliderTextPanelAlwaysOnTopFieldLabel": "文本显示在最前方",
    "SpecialNewsSliderTextPanelOpacityFieldLabel": "透明度",
    "SpecialNewsSliderTextPanelFontFieldLabel": "字体",
    "SpecialNewsSliderTextPanelFontSizeFieldLabel": "字体大小",
    "SpecialNewsSliderTextPanelBackgroundColorFieldLabel": "文本背景颜色",
    "SpecialNewsSliderTextPanelAlignFieldLabel": "文本对齐方式",
    "SpecialNewsSliderTextPanelFontColorFieldLabel": "字体颜色",
    "SpecialNewsSliderNoDataMessage": "请编辑组件来添加新闻",
    "SpecialNewsSliderGeneralPanelEffectsGroupName": "特效",
    "SpecialNewsSliderGeneralPanelTransitionDropdownLabel": "过渡效果",
    "SpecialNewsSliderGeneralPanelTransitionDropdownSlideOptionText":"滑动",
    "SpecialNewsSliderGeneralPanelTransitionDropdownFadeOptionText":"淡出",
    "SpecialNewsSliderGeneralPanelEnableProgressIndicatorToggleLabel": "显示进度",
    "SpecialNewsSliderGeneralPanelEnableArrowsToggleLabel": "显示箭头",
    "SpecialNewsSliderGeneralPanelEnableBulletsToggleLabel": "显示项目符号",
    "SpecialNewsSliderGeneralPanelEnablePlayToggleLabel": "显示播放/暂停按钮",
    "SpecialNewsSliderGeneralPanelEnableFullscreenToggleLabel": "显示全屏控制按钮",
    "SpecialNewsSliderGeneralPanelEnableZoomPanelToggleLabel": "显示缩放控制按钮",
    "SpecialNewsSliderGeneralPanelControlsAlwaysOnToggleLabel": "始终显示控制按钮",
    "SpecialNewsSliderGeneralPanelPreserveRatioToggleLabel": "显示比率",
    "SpecialNewsSliderGeneralPanelPauseOnMouseoverToggleLabel": "鼠标悬停暂停播放新闻",
    "SpecialNewsSliderGeneralPanelCarouselToggleLabel": "轮播",
    "SpecialNewsSliderGeneralPanelAutoplayToggleLabel": "自动播放",
    "SpecialNewsSliderGeneralPanelSpeedSliderLabel": "滑动速度 (毫秒)",
    "SpecialNewsSliderGeneralPanelDataManagementLabel": "新闻",
    "SpecialNewsSliderGeneralPanelDataManagementTableHeaderText": "管理新闻",
    "SpecialNewsSliderGeneralPanelDataManagementTableTitleColumnDisplayName":"标题",
    "SpecialNewsSliderGeneralPanelDataManagementTableEnableColumnDisplayName":"是否可用",
    "SpecialNewsSliderGeneralPanelDataManagementTableDescriptionColumnDisplayName":"新闻简介",
    "SpecialNewsSliderGeneralPanelDataManagementTablePictureColumnDisplayName":"图片",
    "SpecialNewsSliderGeneralPanelDataManagementTableLinkUrlColumnDisplayName":"链接地址"
  }
});